### PR TITLE
use ROBOT enviroment to get machine tag for pr2 robot

### PR DESCRIPTION
**Pull request by k-okada**

### CODE REVIEW

**Comment by furushchev** [comment]
duplicate? https://github.com/jsk-ros-pkg/jsk_smart_apps/pull/54

**Comment by k-okada** [comment]
Oh, I see, you're correct. And the blocker (https://github.com/jsk-ros-pkg/jsk_demos/issues/1031) is not fixed yet

**Comment by furushchev** [comment]
jsk-ros-pkg/jsk_demos#1031 was merged. please merge this PR or #54 if no problem.

**Comment by furushchev** [comment]
ping

**Comment by k-okada** [comment]
sorry for late, restarting travis again. If that passed we'll merge.

**Comment by furushchev** [comment]
travis failed

```bash
]2;[build] 10/21]2;[build] 10/21]2;[build] 10/21]2;[build] 10/21]2;[build] 10/21]2;[build] 10/21]2;[build] 10/21]2;[build] 10/21]2;[build] 10/21]2;[build] 10/21]2;[build] 10/21]2;[build] 10/21]2;[build] 10/21]2;[build] 10/21]2;[build] 10/21]2;[build] 10/21]2;[build] 10/21]2;[build] 10/21]2;[build] 10/21]2;[build] 10/21]2;[build] 10/21]2;[build] 10/21]2;[build] 10/21]2;[build] 10/21]2;[build] 10/21]2;[build] 10/21]2;[build] 10/21]2;[build] 10/21]2;[build] 10/21]2;[build] 10/21]2;[build] 10/21]2;[build] 10/21]2;[build] 10/21]2;[build] 10/21]2;[build] 10/21]2;[build] 10/21]2;[build] 10/21]2;[build] 10/21]2;[build] 10/21]2;[build] 10/21]2;[build] 10/21]2;[build] 10/21]2;[build] 10/21]2;[build] 10/21]2;[build] 10/21]2;[build] 10/21]2;[build] 10/21]2;[build] 10/21]2;[build] 10/21]2;[build] 10/21]2;[build] 10/21]2;[build] 10/21]2;[build] 10/21]2;[build] 10/21]2;[build] 10/21]2;[build] 10/21]2;[build] 10/21[[36mdrc_task_common[0m] [0mg++: internal compiler error: Killed (program cc1plus)[0m        [0m[0m
]2;[build] 10/21[[36mdrc_task_common[0m] Please submit a full bug report,[0m                              [0m[0m
]2;[build] 10/21[[36mdrc_task_common[0m] with preprocessed source if appropriate.[0m                      [0m[0m
]2;[build] 10/21[[36mdrc_task_common[0m] See <file:///usr/share/doc/gcc-4.6/README.Bugs> for instructions.[0m [0m[0m
]2;[build] 10/21[[36mdrc_task_common[0m] make[2]: *** [CMakeFiles/manipulation_data_visualizer.dir/src/drc_task_common/manipulation_data_visualizer.cpp.o] Error 4[0m [0m[0m
]2;[build] 10/21[[36mdrc_task_common[0m] make[1]: *** [CMakeFiles/manipulation_data_visualizer.dir/all] Error 2[0m [0m[0m
]2;[build] 10/21[[36mdrc_task_common[0m] make[1]: *** Waiting for unfinished jobs....[0m                  [0m[0m
]2;[build] 10/21[[36mdrc_task_common[0m] g++: internal compiler error: Killed (program cc1plus)[0m        [0m[0m
]2;[build] 10/21[[36mdrc_task_common[0m] Please submit a full bug report,[0m                              [0m[0m
]2;[build] 10/21[[36mdrc_task_common[0m] with preprocessed source if appropriate.[0m                      [0m[0m
]2;[build] 10/21[[36mdrc_task_common[0m] See <file:///usr/share/doc/gcc-4.6/README.Bugs> for instructions.[0m [0m[0m
]2;[build] 10/21[[36mdrc_task_common[0m] make[2]: *** [CMakeFiles/manipulation_data_server.dir/src/drc_task_common/manipulation_data_server.cpp.o] Error 4[0m [0m[0m
]2;[build] 10/21[[36mdrc_task_common[0m] make[1]: *** [CMakeFiles/manipulation_data_server.dir/all] Error 2[0m [0m[0m
]2;[build] 10/21[[36mdrc_task_common[0m] make: *** [all] Error 2[0m                                       [0m[0m
]2;[build] 10/21[[36mdrc_task_common[0m] [1m[31m<==[0m '[1m/home/travis/ros/ws_jsk_smart_apps/build/drc_task_common/build_env.sh /usr/bin/make --jobserver-fds=3,4 -j[0m' [31mfailed with return code[0m '[1m2[0m'[0m [0m[0m
]2;[build] 10/21[1m[31mFailed[0m   [32m<==[0m [36mdrc_task_common             [0m [ [33m1 minute and 49.7 seconds[0m ][0m         [0m[0m
[build] Calculating new jobs...                                                 [0m[0m
]2;[build] 10/21]2;[build] 10/21]2;[build] There were '2' [1m[31merrors[0m:[0m                                                  [0m[0m
```

restarting...

**Comment by k-okada** [comment]
release new version if this PR passed

**Pull request merged**
