### PR TITLE
Migrate srv files from jsk_pcl_ros to jsk_recognition_msgs

### PR DESCRIPTION
**Pull request by wkentaro**
## Background

Some packages in jsk_visualization depends on jsk_pcl_ros because it uses the srv files.
But jsk_pcl_ros is a very large package and the dependency should be avoided ideally.
The solution is placing `msg/srv` files into `jsk_recognition_msgs`.

## Plans

1. Merge this after `jsk_recognition_msgs` is released: http://repositories.ros.org/status_page/ros_indigo_default.html?q=jsk_recognition_msgs
1. Release this pacakge.
1. Remove `jsk_pcl_ros/srv`.
1. Release `jsk_pcl_ros`.

## Related PRs

- https://github.com/jsk-ros-pkg/jsk_recognition/pull/1827
- https://github.com/jsk-ros-pkg/jsk_recognition/pull/1914

### CODE REVIEW

**Comment by k-okada** [comment]
need to add jsk_recognition from source?

**Comment by wkentaro** [comment]
I'm not sure why, so restarting the CI.

**Comment by k-okada** [comment]
```
+++sh -c '$CI_SOURCE_PATH/.travis_before_script_hydro.bash'
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
     Performing actions: 
     Add new elements:
  jsk_recognition/jsk_recognition_msgs
Config changed, maybe you need run wstool update to update SCM entries.
Overwriting /home/travis/ros/ws_jsk_smart_apps/src/.rosinstall
update complete.
Prepare updating http://github.com/jsk-ros-pkg/jsk_smart_apps (version None) to /home/travis/ros/ws_jsk_smart_apps/src/jsk_smart_apps
Url https://github.com/jsk-ros-pkg/jsk_smart_apps.git does not match http://github.com/jsk-ros-pkg/jsk_smart_apps requested.
  (d)elete and replace, (a)bort, (i)nplace delete and replace at symlink, (s)kip: 
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```
something wrong with the script @wkentaro

**Comment by k-okada** [comment]
```

[jsk_pcl_ros_utils] /home/travis/ros/ws_jsk_smart_apps/src/jsk-ros-pkg/jsk_recognition/jsk_pcl_ros_utils/src/label_to_cluster_point_indices_nodelet.cpp: In member function virtual void jsk_pcl_ros_utils::LabelToClusterPointIndices::subscribe():
[jsk_pcl_ros_utils] /home/travis/ros/ws_jsk_smart_apps/src/jsk-ros-pkg/jsk_recognition/jsk_pcl_ros_utils/src/label_to_cluster_point_indices_nodelet.cpp:60:5: error: warnNoRemap is not a member of jsk_topic_tools
[jsk_pcl_ros_utils] make[2]: *** [CMakeFiles/jsk_pcl_ros_utils.dir/src/label_to_cluster_point_indices_nodelet.cpp.o] Error 1
[jsk_pcl_ros_utils] make[2]: *** Waiting for unfinished jobs....
[jsk_pcl_ros_utils] make[1]: *** [CMakeFiles/jsk_pcl_ros_utils.dir/all] Error 2
```
need to use latest jsk_topic_tools too?

**Comment by k-okada** [comment]
closes via #69

**Pull request closed without merging**
