### PR TITLE
[jsk_android_gui_api9/cameras_and_points_mux.launch] use env ROBOT for including machine tags

### PR DESCRIPTION
**Pull request by furushchev**
This is necessary for launching with pr2_gazebo

### CODE REVIEW

**Comment by aginika** [comment]
+1

**Comment by k-okada** [comment]
I prefer to use param or host name

2015年7月30日木曜日、Yuto Inagaki<notifications@github.com>さんは書きました:

> +1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_smart_apps/pull/54#issuecomment-126223200>
> .
>


-- 
--
◉ Kei Okada

**Comment by garaemon** [comment]
> I prefer to use param or host name

I think we cannot expand parameter in launch file by `$(param foo)`.

**Comment by k-okada** [comment]
using env ROBOT for loading machine tag is ok for  now https://github.com/PR2/pr2_navigation/blob/86fa20c703bc349b24bb18001c48ac87d18bb7e6/pr2_navigation_slam/move_base.xml#L2

travis failed to compile drc_task_common, specify TEST_PKGS or remove jsk_dmoes from .rosinstall, 
I would say later version of jsk_travis will check the code more seriously, so updating .travis will not help you to pass tests.

**Pull request closed without merging**
