### PR TITLE
Catkinize local app manager and its dependencies

### PR DESCRIPTION
**Pull request by furushchev**
catkinized `local_app_manager` package and its dependencies.
I could not understand `jsk_android_gui_api9` so I now left temporally empty catkin make file.

### CODE REVIEW

**Comment by garaemon** [comment]
This is roseus bug

```
-- jsk_smart_gui: 0 messages, 1 services
CMake Error: Attempt to add a custom rule to output "/home/travis/ros/ws_jsk_smart_apps/devel/share/roseus/ros/jsk_smart_gui/manifest.l.rule" which already has a custom rule.
CMake Error at /home/travis/ros/ws_jsk_smart_apps/build/jsk_smart_apps/jsk_smart_gui/cmake/jsk_smart_gui-genmsg.cmake:65 (add_custom_target):
  add_custom_target cannot create target
  "jsk_smart_gui_generate_messages_eus" because another target with the same
  name already exists.  The existing target is a custom target created in
  source directory
  "/home/travis/ros/ws_jsk_smart_apps/src/jsk_smart_apps/jsk_smart_gui".  See
  documentation for policy CMP0002 for more details.
Call Stack (most recent call first):
  /opt/ros/hydro/share/genmsg/cmake/genmsg-extras.cmake:299 (include)
  jsk_smart_apps/jsk_smart_gui/catkin.cmake:17 (generate_messages)
  jsk_smart_apps/jsk_smart_gui/CMakeLists.txt:2 (include)
```

**Comment by garaemon** [comment]
jsk_demos are not yet released...??

```
CMake Error at /opt/ros/hydro/share/catkin/cmake/catkinConfig.cmake:75 (find_package):
  Could not find a configuration file for package
  detect_cans_in_fridge_201202.
  Set detect_cans_in_fridge_201202_DIR to the directory containing a CMake
  configuration file for detect_cans_in_fridge_201202.  The file will have
  one of the following names:
    detect_cans_in_fridge_201202Config.cmake
    detect_cans_in_fridge_201202-config.cmake

```

**Comment by garaemon** [comment]
Oh, jsk_demos is not released as deb.

@furushchev 
Please add jsk_demos to .rosinstall

**Comment by k-okada** [comment]
if you do not have any reason to keep old rtmbuild/rosmake settings, you
can remove manifest.xml and rename catkin.cmake to CMakeLists.txt

--
◉ Kei Okada

**Comment by furushchev** [comment]
still failed. in progress https://github.com/jsk-ros-pkg/jsk_demos/pull/181

**Comment by furushchev** [comment]
@k-okada OK.

**Comment by furushchev** [comment]
sorry please restart travis again

**Comment by garaemon** [comment]
restarted

**Comment by furushchev** [comment]
I always had the question. there is no directory roseus in `$HOME/.ros` In your environment?

**Comment by k-okada** [comment]
.ros/roseus is deprecated,

--
◉ Kei Okada

**Comment by garaemon** [comment]
snapmap?

**Comment by furushchev** [comment]
sorry i added to .rosinstall.  now travis passed. please merge! :+1:

**Comment by furushchev** [comment]
and also please restart travis of https://github.com/jsk-ros-pkg/jsk_demos/pull/177

**Pull request merged**
